runtime: nodejs20

service: balinese-date-api # Specify the service name

handlers:
  - url: /.*
    script: auto

automatic_scaling:
  max_instances: 1

#entrypoint: ./entrypoint.sh # Use your custom start script